CREATE TABLE `USER_TB` (
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_nm`	VARCHAR(20)	NOT NULL,
	`user_email`	VARCHAR(30)	NOT NULL,
	`pwd`	VARCHAR(30)	NOT NULL,
	`telno`	INT	NOT NULL,
	`subs_dt`	DATE	NOT NULL,
	`gender`	VARCHAR(10)	NOT NULL	COMMENT '프론트에서 (남,여,상관없음) 중 하나는 무조건 오기에  not null',
	`bryr`	DATE	NOT NULL,
	`prvc_arge`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`user_cls_cd`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT '관리자:TRUE, 유저:NULL',
	`rcmdr_email`	VARCHAR(30)	NULL,
	`pnt`	INT	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `CART_TB` (
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_qty`	INT	NOT NULL	DEFAULT '1',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NULL
);

CREATE TABLE `ORDER_TB` (
	`ord_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`addr_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`coupn_id`	INT	NOT NULL	COMMENT 'AUTO INCREMENT',
	`stus_cd`	VARCHAR(30)	NOT NULL	COMMENT '주문대기, 주문완료, 주문취소, 주문오류',
	`req_plc_cd`	VARCHAR(30)	NOT NULL	COMMENT '문 앞, 경비실, 택배함',
	`req_dtls`	VARCHAR(100)	NULL,
	`used_acamt`	INT	NOT NULL,
	`dlvr_yn`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '배송 직후, 수신 거부',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `COMMON_CODE_TB` (
	`cd`	VARCHAR(5)	NOT NULL,
	`cd_type_id`	VARCHAR(10)	NOT NULL,
	`cd_name`	VARCHAR(10)	NOT NULL	COMMENT 'EX)콩나물·버섯',
	`brief_desc`	VARCHAR(50)	NULL,
	`long_desc`	VARCHAR(150)	NULL,
	`order`	INT	NOT NULL,
	`is_use`	BOOLEAN	NOT NULL	DEFAULT false,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `BOARD_TB` (
	`bbs_id`	INT	NOT NULL	COMMENT 'auto increment, PK',
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`bbs_title`	VARCHAR(60)	NOT NULL,
	`wrt_dt`	DATE	NOT NULL,
	`user_name`	VARCHAR(20)	NOT NULL,
	`bbs_clsf_cd`	VARCHAR(30)	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `BOARD_CONTENT_TB` (
	`bbs_id`	INT	NOT NULL,
	`bbs_cn`	TEXT	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `REVIEW_BOARD_TB` (
	`bbs_id`	INT	NOT NULL,
	`revw_like`	INT	NOT NULL	DEFAULT '0',
	`revw_img`	VARCHAR(255)	NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `INQ_BOARD_TB` (
	`bbs_id`	INT	NOT NULL,
	`is_secret`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT 'true면 비밀글',
	`is_replied`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT 'true면 답변완료',
	`inq_reg_date`	DATETIME	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`int_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `ANSWER_TB` (
	`bbs_id`	INT	NOT NULL,
	`inq_ans`	TEXT	NOT NULL,
	`ans_dt`	DATETIME	NOT NULL,
	`gd_cd`	VARCHAR(10)	NOT NULL,
	`in_date`	DATETIME	NULL	DEFAULT now(),
	`int_user`	VARCHAR(30)	NULL,
	`up_date`	DATETIME	NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NULL
);

CREATE TABLE `ADDRESS_TB` (
	`addr_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`addr`	VARCHAR(30)	NULL,
	`ba_addr`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`chk_addr`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`add_code`	VARCHAR(30)	NOT NULL,
	`stna_addr`	VARCHAR(50)	NOT NULL,
	`stna_addr_dt`	VARCHAR(50)	NOT NULL,
	`area_addr`	VARCHAR(50)	NOT NULL,
	`area_addr_dt`	VARCHAR(50)	NOT NULL,
	`deli_type`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT 'T:새벽배송, F:낮배송',
	`city_code`	VARCHAR(30)	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `ORDER_LOG_TB` (
	`ord_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`ord_nm`	VARCHAR(20)	NOT NULL,
	`ord_mobl`	VARCHAR(20)	NOT NULL,
	`ord_stus_cd`	VARCHAR(30)	NOT NULL	COMMENT '주문대기, 주문완료, 주문취소, 주문오류',
	`ord_dcrs_dtm`	DATETIME	NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `PAYMENT_TB` (
	`ord_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`setl_cd`	VARCHAR(30)	NOT NULL	COMMENT '신용카드, 간편결제, 휴대폰',
	`setl_stus_cd`	VARCHAR(30)	NOT NULL	COMMENT '결제중, 결제완료, 결제취소, 결제오류',
	`all_amt`	INT	NOT NULL,
	`all_dc_amt`	INT	NOT NULL,
	`dlvr_amt`	INT	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `EVENT_TB` (
	`event_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`coupn_id`	INT	NOT NULL,
	`nm`	VARCHAR(50)	NOT NULL,
	`desc`	VARCHAR(200)	NULL,
	`image`	VARCHAR(100)	NULL,
	`mft`	VARCHAR(50)	NULL,
	`setl_methd_cd`	VARCHAR(10)	NULL,
	`stpt_dd`	DATETIME	NOT NULL,
	`expi_dd`	DATETIME	NOT NULL,
	`early_end_stus`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`ds_rate`	INT	NOT NULL	DEFAULT '0',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `PRODUCT_TB` (
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`cat_code`	VARCHAR(50)	NULL,
	`price`	INT	NOT NULL	DEFAULT '0',
	`image`	VARCHAR(255)	NOT NULL,
	`ds_rate`	INT	NOT NULL	DEFAULT '0',
	`sel_price`	INT	NOT NULL	DEFAULT '0',
	`title`	VARCHAR(50)	NOT NULL,
	`sub_title`	VARCHAR(50)	NOT NULL,
	`rec_info`	VARCHAR(50)	NULL,
	`adt_sts`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`stock`	INT	NOT NULL	DEFAULT '0',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `ORDER_PRODUCT_TB` (
	`ord_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_qty`	INT	NOT NULL	DEFAULT '1',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `USER_TIER_BNFT_TB` (
	`gd_cd`	VARCHAR(10)	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`gd_nm`	VARCHAR(10)	NOT NULL	DEFAULT '일반',
	`gd_rate`	INT	NOT NULL,
	`coupn_id`	INT	NULL,
	`revw_acamt`	INT	NULL,
	`mmby_gift`	VARCHAR(20)	NULL,
	`acmlt_py_cnd`	INT	NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `USER_INFO_TB` (
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`coupn_id`	INT	NOT NULL	COMMENT 'AUTO INCREMENT',
	`pnt_hist_id`	INT	NOT NULL,
	`gd_cd`	VARCHAR(10)	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`subs_state`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`in_update`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `USER_MOD_INFO_TB` (
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`prvc_cd`	VARCHAR(10)	NOT NULL	COMMENT '이메일,비밀번호,이름,성별,생년월일',
	`content`	VARCHAR(10)	NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `EVENT_PRODUCT_LIST_TB` (
	`event_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `PRODUCT_DETAIL_TB` (
	`det_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pack_cd`	VARCHAR(30)	NOT NULL	COMMENT '상온, 냉장, 냉동',
	`sell_cd`	VARCHAR(30)	NOT NULL,
	`weca_cd`	VARCHAR(30)	NOT NULL,
	`allg_dt`	VARCHAR(30)	NULL,
	`ex_dt`	VARCHAR(30)	NULL,
	`origin`	VARCHAR(20)	NULL,
	`notice`	VARCHAR(30)	NULL,
	`prt_info`	TEXT	NOT NULL,
	`prt_image`	VARCHAR(255)	NULL,
	`company`	VARCHAR(20)	NULL,
	`de_type`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT 'T:새벽배송, F:낮배송',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `PRODUCT_TAG_TB` (
	`tag_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `TAG_TB` (
	`tag_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`tag_name`	VARCHAR(50)	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `NON_USER_TB` (
	`email`	VARCHAR(30)	NOT NULL,
	`id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`mobl`	VARCHAR(20)	NOT NULL,
	`sel_terms`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`dlvr_info`	VARCHAR(30)	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `KURLYPAY_POINT_HIST_TB` (
	`pnt_hist_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`odr_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`chng_pnt`	INT	NOT NULL,
	`pnt_chng_dt`	TIMESTAMP	NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `COUPON_TB` (
	`coupn_id`	INT	NOT NULL	COMMENT 'AUTO INCREMENT',
	`event_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL	COMMENT 'AUTO INCREMENT',
	`nm`	VARCHAR(50)	NOT NULL,
	`ds_max_posbl_amt`	INT	NULL,
	`use_cnd`	VARCHAR(50)	NULL,
	`lmtt_cnd`	VARCHAR(50)	NULL,
	`func`	VARCHAR(10)	NOT NULL,
	`rate`	DECIMAL(3,2)	NOT NULL,
	`used`	BOOLEAN	NOT NULL,
	`expi_dd`	DATETIME	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `PRICE_CHANGE_HISTORY_TB` (
	`his_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`bf_date`	DATE	NOT NULL,
	`ar_date`	DATE	NOT NULL,
	`price`	INT	NOT NULL	DEFAULT '0',
	`his_rsn`	VARCHAR(50)	NOT NULL,
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `USER_WISHLIST_TB` (
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `SKU_TB` (
	`st_hi_id`	INT	NOT NULL,
	`pdt_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`stock`	INT	NOT NULL,
	`st_in_date`	DATETIME	NOT NULL,
	`st_out_date`	DATETIME	NOT NULL,
	`sku_code`	VARCHAR(100)	NOT NULL	COMMENT 'SKU관리',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `USER_COUPON_TB` (
	`coupn_id`	INT	NOT NULL	COMMENT 'AUTO INCREMENT',
	`user_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `PAYMENT_LOG_TB` (
	`ord_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`setl_stus_cd`	VARCHAR(30)	NOT NULL,
	`setl_mn_cd`	VARCHAR(30)	NOT NULL	COMMENT '신용카드, 간편결제, 휴대폰',
	`setl_amt`	INT	NOT NULL,
	`setl_dtm`	DATETIME	NOT NULL,
	`in_date`	DATETIME	NOT NULL,
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL,
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `DELIVERY_LOG_TB` (
	`order_id`	INT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`rcv_nm`	VARCHAR(30)	NOT NULL,
	`rcv_mobl`	VARCHAR(30)	NOT NULL,
	`all_addr`	VARCHAR(100)	NOT NULL	COMMENT '주소 + 상세 주소',
	`req_dtls`	VARCHAR(100)	NULL,
	`dlvr_stus_cd`	VARCHAR(30)	NOT NULL	COMMENT '배송대기, 배송중, 배송완료',
	`pack_typ_cd`	VARCHAR(30)	NOT NULL	COMMENT '상온, 냉장, 냉동',
	`dlvr_yn`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '배송 직후, 수신 거부',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `COMMON_CODE_TYPE_TB` (
	`cd_type_id`	VARCHAR(10)	NOT NULL,
	`up_cd`	VARCHAR(5)	NOT NULL,
	`up_cd_type_id`	VARCHAR(10)	NOT NULL,
	`cd_type_name`	VARCHAR(10)	NOT NULL	COMMENT 'EX)채소',
	`in_date`	DATETIME	NOT NULL	DEFAULT now(),
	`in_user`	VARCHAR(30)	NOT NULL,
	`up_date`	DATETIME	NOT NULL	DEFAULT now(),
	`up_user`	VARCHAR(30)	NOT NULL
);

ALTER TABLE `USER_TB` ADD CONSTRAINT `PK_USER_TB` PRIMARY KEY (
	`user_id`
);

ALTER TABLE `CART_TB` ADD CONSTRAINT `PK_CART_TB` PRIMARY KEY (
	`user_id`,
	`pdt_id`
);

ALTER TABLE `ORDER_TB` ADD CONSTRAINT `PK_ORDER_TB` PRIMARY KEY (
	`ord_id`
);

ALTER TABLE `COMMON_CODE_TB` ADD CONSTRAINT `PK_COMMON_CODE_TB` PRIMARY KEY (
	`cd`,
	`cd_type_id`
);

ALTER TABLE `BOARD_TB` ADD CONSTRAINT `PK_BOARD_TB` PRIMARY KEY (
	`bbs_id`
);

ALTER TABLE `BOARD_CONTENT_TB` ADD CONSTRAINT `PK_BOARD_CONTENT_TB` PRIMARY KEY (
	`bbs_id`
);

ALTER TABLE `REVIEW_BOARD_TB` ADD CONSTRAINT `PK_REVIEW_BOARD_TB` PRIMARY KEY (
	`bbs_id`
);

ALTER TABLE `INQ_BOARD_TB` ADD CONSTRAINT `PK_INQ_BOARD_TB` PRIMARY KEY (
	`bbs_id`
);

ALTER TABLE `ANSWER_TB` ADD CONSTRAINT `PK_ANSWER_TB` PRIMARY KEY (
	`bbs_id`
);

ALTER TABLE `ADDRESS_TB` ADD CONSTRAINT `PK_ADDRESS_TB` PRIMARY KEY (
	`addr_id`
);

ALTER TABLE `ORDER_LOG_TB` ADD CONSTRAINT `PK_ORDER_LOG_TB` PRIMARY KEY (
	`ord_id`
);

ALTER TABLE `PAYMENT_TB` ADD CONSTRAINT `PK_PAYMENT_TB` PRIMARY KEY (
	`ord_id`
);

ALTER TABLE `EVENT_TB` ADD CONSTRAINT `PK_EVENT_TB` PRIMARY KEY (
	`event_id`
);

ALTER TABLE `PRODUCT_TB` ADD CONSTRAINT `PK_PRODUCT_TB` PRIMARY KEY (
	`pdt_id`
);

ALTER TABLE `ORDER_PRODUCT_TB` ADD CONSTRAINT `PK_ORDER_PRODUCT_TB` PRIMARY KEY (
	`ord_id`,
	`pdt_id`
);

ALTER TABLE `USER_TIER_BNFT_TB` ADD CONSTRAINT `PK_USER_TIER_BNFT_TB` PRIMARY KEY (
	`gd_cd`
);

ALTER TABLE `USER_INFO_TB` ADD CONSTRAINT `PK_USER_INFO_TB` PRIMARY KEY (
	`user_id`
);

ALTER TABLE `USER_MOD_INFO_TB` ADD CONSTRAINT `PK_USER_MOD_INFO_TB` PRIMARY KEY (
	`user_id`
);

ALTER TABLE `EVENT_PRODUCT_LIST_TB` ADD CONSTRAINT `PK_EVENT_PRODUCT_LIST_TB` PRIMARY KEY (
	`event_id`,
	`pdt_id`
);

ALTER TABLE `PRODUCT_DETAIL_TB` ADD CONSTRAINT `PK_PRODUCT_DETAIL_TB` PRIMARY KEY (
	`det_id`,
	`pdt_id`
);

ALTER TABLE `PRODUCT_TAG_TB` ADD CONSTRAINT `PK_PRODUCT_TAG_TB` PRIMARY KEY (
	`tag_id`,
	`pdt_id`
);

ALTER TABLE `TAG_TB` ADD CONSTRAINT `PK_TAG_TB` PRIMARY KEY (
	`tag_id`
);

ALTER TABLE `NON_USER_TB` ADD CONSTRAINT `PK_NON_USER_TB` PRIMARY KEY (
	`email`,
	`id`
);

ALTER TABLE `KURLYPAY_POINT_HIST_TB` ADD CONSTRAINT `PK_KURLYPAY_POINT_HIST_TB` PRIMARY KEY (
	`pnt_hist_id`,
	`user_id`
);

ALTER TABLE `COUPON_TB` ADD CONSTRAINT `PK_COUPON_TB` PRIMARY KEY (
	`coupn_id`
);

ALTER TABLE `PRICE_CHANGE_HISTORY_TB` ADD CONSTRAINT `PK_PRICE_CHANGE_HISTORY_TB` PRIMARY KEY (
	`his_id`,
	`pdt_id`
);

ALTER TABLE `USER_WISHLIST_TB` ADD CONSTRAINT `PK_USER_WISHLIST_TB` PRIMARY KEY (
	`pdt_id`,
	`user_id`
);

ALTER TABLE `SKU_TB` ADD CONSTRAINT `PK_SKU_TB` PRIMARY KEY (
	`st_hi_id`,
	`pdt_id`
);

ALTER TABLE `USER_COUPON_TB` ADD CONSTRAINT `PK_USER_COUPON_TB` PRIMARY KEY (
	`coupn_id`,
	`user_id`
);

ALTER TABLE `PAYMENT_LOG_TB` ADD CONSTRAINT `PK_PAYMENT_LOG_TB` PRIMARY KEY (
	`ord_id`
);

ALTER TABLE `DELIVERY_LOG_TB` ADD CONSTRAINT `PK_DELIVERY_LOG_TB` PRIMARY KEY (
	`order_id`
);

ALTER TABLE `COMMON_CODE_TYPE_TB` ADD CONSTRAINT `PK_COMMON_CODE_TYPE_TB` PRIMARY KEY (
	`cd_type_id`
);

ALTER TABLE `CART_TB` ADD CONSTRAINT `FK_USER_TB_TO_CART_TB_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER_TB` (
	`user_id`
);

ALTER TABLE `CART_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_CART_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `COMMON_CODE_TB` ADD CONSTRAINT `FK_COMMON_CODE_TYPE_TB_TO_COMMON_CODE_TB_1` FOREIGN KEY (
	`cd_type_id`
)
REFERENCES `COMMON_CODE_TYPE_TB` (
	`cd_type_id`
);

ALTER TABLE `BOARD_CONTENT_TB` ADD CONSTRAINT `FK_BOARD_TB_TO_BOARD_CONTENT_TB_1` FOREIGN KEY (
	`bbs_id`
)
REFERENCES `BOARD_TB` (
	`bbs_id`
);

ALTER TABLE `REVIEW_BOARD_TB` ADD CONSTRAINT `FK_BOARD_TB_TO_REVIEW_BOARD_TB_1` FOREIGN KEY (
	`bbs_id`
)
REFERENCES `BOARD_TB` (
	`bbs_id`
);

ALTER TABLE `INQ_BOARD_TB` ADD CONSTRAINT `FK_BOARD_TB_TO_INQ_BOARD_TB_1` FOREIGN KEY (
	`bbs_id`
)
REFERENCES `BOARD_TB` (
	`bbs_id`
);

ALTER TABLE `ANSWER_TB` ADD CONSTRAINT `FK_INQ_BOARD_TB_TO_ANSWER_TB_1` FOREIGN KEY (
	`bbs_id`
)
REFERENCES `INQ_BOARD_TB` (
	`bbs_id`
);

ALTER TABLE `ORDER_LOG_TB` ADD CONSTRAINT `FK_ORDER_TB_TO_ORDER_LOG_TB_1` FOREIGN KEY (
	`ord_id`
)
REFERENCES `ORDER_TB` (
	`ord_id`
);

ALTER TABLE `PAYMENT_TB` ADD CONSTRAINT `FK_ORDER_TB_TO_PAYMENT_TB_1` FOREIGN KEY (
	`ord_id`
)
REFERENCES `ORDER_TB` (
	`ord_id`
);

ALTER TABLE `ORDER_PRODUCT_TB` ADD CONSTRAINT `FK_ORDER_TB_TO_ORDER_PRODUCT_TB_1` FOREIGN KEY (
	`ord_id`
)
REFERENCES `ORDER_TB` (
	`ord_id`
);

ALTER TABLE `ORDER_PRODUCT_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_ORDER_PRODUCT_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `USER_INFO_TB` ADD CONSTRAINT `FK_USER_TB_TO_USER_INFO_TB_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER_TB` (
	`user_id`
);

ALTER TABLE `USER_MOD_INFO_TB` ADD CONSTRAINT `FK_USER_TB_TO_USER_MOD_INFO_TB_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER_TB` (
	`user_id`
);

ALTER TABLE `EVENT_PRODUCT_LIST_TB` ADD CONSTRAINT `FK_EVENT_TB_TO_EVENT_PRODUCT_LIST_TB_1` FOREIGN KEY (
	`event_id`
)
REFERENCES `EVENT_TB` (
	`event_id`
);

ALTER TABLE `EVENT_PRODUCT_LIST_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_EVENT_PRODUCT_LIST_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `PRODUCT_DETAIL_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_PRODUCT_DETAIL_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `PRODUCT_TAG_TB` ADD CONSTRAINT `FK_TAG_TB_TO_PRODUCT_TAG_TB_1` FOREIGN KEY (
	`tag_id`
)
REFERENCES `TAG_TB` (
	`tag_id`
);

ALTER TABLE `PRODUCT_TAG_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_PRODUCT_TAG_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `NON_USER_TB` ADD CONSTRAINT `FK_ORDER_TB_TO_NON_USER_TB_1` FOREIGN KEY (
	`id`
)
REFERENCES `ORDER_TB` (
	`ord_id`
);

ALTER TABLE `KURLYPAY_POINT_HIST_TB` ADD CONSTRAINT `FK_USER_TB_TO_KURLYPAY_POINT_HIST_TB_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER_TB` (
	`user_id`
);

ALTER TABLE `PRICE_CHANGE_HISTORY_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_PRICE_CHANGE_HISTORY_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `USER_WISHLIST_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_USER_WISHLIST_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `USER_WISHLIST_TB` ADD CONSTRAINT `FK_USER_TB_TO_USER_WISHLIST_TB_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER_TB` (
	`user_id`
);

ALTER TABLE `SKU_TB` ADD CONSTRAINT `FK_PRODUCT_TB_TO_SKU_TB_1` FOREIGN KEY (
	`pdt_id`
)
REFERENCES `PRODUCT_TB` (
	`pdt_id`
);

ALTER TABLE `USER_COUPON_TB` ADD CONSTRAINT `FK_COUPON_TB_TO_USER_COUPON_TB_1` FOREIGN KEY (
	`coupn_id`
)
REFERENCES `COUPON_TB` (
	`coupn_id`
);

ALTER TABLE `USER_COUPON_TB` ADD CONSTRAINT `FK_USER_TB_TO_USER_COUPON_TB_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER_TB` (
	`user_id`
);

ALTER TABLE `PAYMENT_LOG_TB` ADD CONSTRAINT `FK_PAYMENT_TB_TO_PAYMENT_LOG_TB_1` FOREIGN KEY (
	`ord_id`
)
REFERENCES `PAYMENT_TB` (
	`ord_id`
);

ALTER TABLE `DELIVERY_LOG_TB` ADD CONSTRAINT `FK_ORDER_TB_TO_DELIVERY_LOG_TB_1` FOREIGN KEY (
	`order_id`
)
REFERENCES `ORDER_TB` (
	`ord_id`
);

